DROP TABLE maintenance_tool CASCADE CONSTRAINTS;

DROP TABLE maintenance CASCADE CONSTRAINTS;

DROP TABLE tool CASCADE CONSTRAINTS;

DROP TABLE maintenance_status CASCADE CONSTRAINTS;

DROP TABLE employee CASCADE CONSTRAINTS;

